### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by mickfuzz** [trollsofthenorth/ludumdare35#3]
Hi there, 
Is this under an open licence I'd like to use it for educational use here if possible
https://github.com/webgameclubs/edlab-gamemakers-club

Mick

**Comment by ellieayla** [comment]
@mickfuzz it was never licensed, but it _could_ be without too much hassle. What would you want to use it for? Do you have a specific license (eg MIT, Apache, GPL) in mind?

**Comment by ellieayla** [comment]
cc: @danieldsj @Myrmidor @gabe-camp

**Comment by mickfuzz** [comment]
Any of those would be great, my repo is cc-by-sa so could incoporate those. Or even a comment saying it is ok to use the coe for the repo below. 

The project aims to find and alter phaser and similar games to make them easily hackable by students aiming to teach game making concepts. There's some more info here 
https://github.com/webgameclubs/edlab-gamemakers-club

Many thanks for considering this.

**Comment by ellieayla** [comment]
Created issue #4

**Comment by ellieayla** [comment]
@mickfuzz All contributors agreed, and this is now licensed with Apache2. Do what you will.
